### ISSUE TITLE
Testing Needed for move-containerfile-to-root Branch

### ISSUE THREAD

**Issue by danloveg** [NationalCentreTruthReconciliation/Secure-Record-Transfer#190]
The following branch has a number of changes that need to be tested in both Windows and ARM-based MacOS: https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/tree/move-containerfile-to-root

I wrote this branch on my laptop running Fedora 40, which uses [SELinux](https://www.redhat.com/en/topics/linux/what-is-selinux). Because of this, I had to add `:z` labels to the volumes in the compose files. I don't know if these volume labels will break the configuration in MacOS or Windows. If they *do* break the app such that it can't be run in Windows or MacOS, the labels should be changed back to `:ro`. Supporting SELinux is not one of the requirements of this application, so we don't need to really worry about breaking it so that it doesn't work with SELinux systems.

There is also a new multi-step build used in the `Containerfile`. Verify that the yuglify binary gets built, and that it gets copied to the Python image and is picked up by the `YUGLIFY_BINARY` setting.

Also, the new behaviour needed to run the app needs to be added to the README and to the docs.

**Comment by yenaing-oo** [comment]
The app ran fine in development since static assets were being served directly from their original location without being minified. In production, however, Django couldn't seem to location `manage.py`:

![image](https://github.com/user-attachments/assets/298a36ef-87a8-4521-87c9-70316ed3b2ef)

I looked through the container's files and discovered that the **contents** of `./bagitobjecttransfer` were copied into `/app` rather than the directory iteself:
![image](https://github.com/user-attachments/assets/1c5d710f-39a5-48b7-b334-93a1989e78d6)

I think the Docker's `COPY` instruction copies the contents of a directory instead of the directory. Here's a similar [question ](https://stackoverflow.com/questions/26504846/copy-directory-to-another-directory-using-add-command)on Stackoverflow, but for the `ADD` instruction.

I changed the part in `Containerfile` copying sources files to copy files and directory separately, and this seemed to fix issue of `manage.py` not being found.

The next issue I ran into is that Django keeps trying to serve static assets from  `app/static` rather than `app/bagitobjecttransfer/static`. (I don't know how to recreate the error logs for this, I got another error instead when going back to this point).

I tried changing every possible setting in `base.py` to make it look for static files in the latter, but nothing seemed to work. The only thing that does work is changing `STATIC_ROOT` to the `app/static`.

**Comment by danloveg** [comment]
See pull request - #197

**Comment by yenaing-oo** [comment]
The Yuglify binary does get built and can be found in `/app/node_modules/yuglify/dist`:
![image](https://github.com/user-attachments/assets/40a787b5-2a84-4d17-891d-3d9ac83bfe30)

When requesting the home page, `ngix`'s logs show that the minified assets are served:
![image](https://github.com/user-attachments/assets/147c27e3-f589-404b-9682-45911bb5a956)

The container's `/static` volume also contains the minified assets, which means the Yuglify binary is being picked up by the `YUGLIFY_BINARY` setting:
![image](https://github.com/user-attachments/assets/bf0b24e1-a3b5-4be7-acf0-eb095845d238)

I'm not sure how to test whether the app _breaks_ due to the changes made by changing the volume labels to `:z`. Could you advise on this?

**Comment by danloveg** [comment]
About the `:z` labels - I just wanted to see if it ran on other machines than mine, and yes it does.

**Comment by danloveg** [comment]
Addressed by #197.
