### ISSUE TITLE
Allow admins to edit any metadata.

### ISSUE THREAD

**Issue by whikloj** [NationalCentreTruthReconciliation/Secure-Record-Transfer#78]
So they can make edits before generating the final BagIt bag.

**Comment by danloveg** [comment]
This change will require the caais_metadata JSON field to be changed to database models. This is a non-trivial change, but should be considered highest priority.

**Any new models and forms should be created in a `caais` app, separate from `recordtransfer` for reusability**. I can foresee the `caais` app and its database models being created in a separate Django repository that can be re-used in other applications (but this does not need to happen yet).

As this is a very large change, I've split the changes up into several pieces:

## New Database Models

The following models should be created for maximum compatibility with the [CAAIS standard](http://archivescanada.ca/uploads/files/Documents/CAAIS_2019May15_EN.pdf).

- `CaaisMetadata`, with members:
  - repository `CharField`
  - accession_title `CharField`
  - archival_unit `CharField`
  - acquisition_method `CharField`
  - disposition_authority `CharField`
  - status `CharField`
  - date_of_material `CharField`
    - _Should_ be a DateTimeField, but I'd rather this field be less restrictive at the expense of being harder to parse
  - rules_or_conventions `TextField`
  - language_of_accession_record `TextField`

- `CaaisSourceType` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='source_types', ...)`
  - source_type `CharField`
  - source_name `CharField`
  - source_role `CharField`
  - source_note `TextField`
  - source_confidentiality `TextField`

- `CaaisContactInformation` with members:
  - source_type `OneToOneField(CaaisSourceType, related_name='contact_info', ...)`
  - address_line_1 `TextField`
  - address_line_2 `TextField`
  - city `TextField`
  - province_or_state `TextField`
  - postal_or_zip_code `CharField`
  - country `CharField`
    - Should use ISO Alpha 3

- `CaaisPreliminaryCustodialHistory` with members:
  - source_type `ForeignKey(CaaisMetadata, related_name='preliminary_custodial_histories', ...)`
  - preliminary_custodial_history `TextField`

- `CaaisExtentStatement` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='extent_statements', ...)
  - extent_type `CharField`
  - quantity_and_unit_of_measure `CharField`
  - content_type `CharField`
  - carrier_type `CharField`
  - digital_file_formats `CharField`
  - extent_note `TextField`

- `CaaisPreliminaryScopeAndContent` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='preliminary_scope_and_contents', ...)`
  - preliminary_scope_and_content `TextField`

- `CaaisLanguageOfMaterial` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='language_of_materials', ...)`
  - language_of_material `TextField`
 
- `CaaisStorageLocation` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='storage_locations', ...)`
  - storage_location `TextField`

- `CaaisRight` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='rights', ...)`
  - rights_type `CharField`
  - rights_value `TextField`
  - rights_note `TextField`

- `CaaisPreservationRequirement` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='presevation_requirements', ...)`
  - preservation_requirement_type `CharField`
  - preservation_requirement_value `TextField`
  - preservation_requirement_note `TextField`

- `CaaisAppraisal` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='appraisals', ...)`
  - appraisal_type `CharField`
  - appraisal_value `TextField`
  - appraisal_note `TextField`

- `CaaisAssociatedDocumentation` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='associated_documentations', ...)`
  - associated_documentation_type `CharField`
  - associated_documentation_title `TextField`
  - associated_documentation_note `TextField`

- `CaaisEvent` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='events', ...)`
  - event_date `DateTimeField`
  - event_agent `ForeignKey(get_user_model(), related_name='events', ...)`
    - `from django.contrib.auth import get_user_model`
  - event_note `TextField`

- `CaaisGeneralNote` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='general_notes', ...)`
  - general_note `TextField`

- `CaaisDateOfCreationOrRevision` with members:
  - metadata `ForeignKey(CaaisMetadata, related_name='date_of_creation_or_revisions', ...)`
  - creation_or_revision_type `CharField`
  - creation_or_revision_date `DateTimeField`
  - creation_or_revision_agent `ForeignKey(get_user_model(), related_name='date_of_creation_or_revisions', ...)`
    - `from django.contrib.auth import get_user_model`
  - creation_or_revision_note `TextField`

## Administrator

The `CaaisMetadata` model should be registered to the admin panel, and an inline model admin created for each of its reverse-foreign-key-related models. This will be a huge form, but I don't know how to get around including all the forms in one admin page.

## transfer_forms.py

It may be possible to create ModelForms for each of the new models, which would reduce the amount of code needed to process the user's POST submissions into CAAIS metadata.

## caais.py

`caais.py` may not be needed anymore, especially if the forms are connected to the models, and create models instances when the forms are saved.

If `caais.py` is still needed, it should be moved to the new `caais` app.

## models.py

Minimal changes needed here. The caais_metadata TextField should be changed to a OneToOneField pointing to `CaaisMetadata`. The bag save logic will need to be updated so that the bag-info.txt is saved when CaaisMetadata is updated. This should likely be a `pre_save` or `post_save` signal on either `CaaisMetadata` or `Bag`.

**Comment by danloveg** [comment]
I've begun to implement the new models and admin on the branch [issue-78](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/tree/issue-78). The admin for section 1 of CAAIS has been implemented so far, and looks like this:

![localhost_8000_admin_caais_metadata_1_change_](https://user-images.githubusercontent.com/28608038/160697623-153f608a-193f-4ea7-ac28-aeed622d6bab.png)

**Comment by danloveg** [comment]
Section 2 is complete. Work is slow-going on this, I expect each CAAIS section (minus section 6) to take about a day's worth of work to write.

**Comment by whikloj** [comment]
Can I help you on this @danloveg? I'm not sure I understand how you are planning this, but it does seem like a lot of work so if I can take part of it off your shoulders, let me know.

**Comment by danloveg** [comment]
Thanks for the offer, I'll need your help in two places, integrating the new models into the rest of the app, and testing and reviewing the code prior to me merging it into the master branch.

Work has temporarily stalled but I'll start it back up as soon as I can. If you wanted to see how things are looking, check out [models.py on the issue-78 branch](https://github.com/NationalCentreTruthReconciliation/Secure-Record-Transfer/blob/issue-78/bagitobjecttransfer/caais/models.py). Line 101 has the top-level `Metadata` model; I got to section 4 of CAAIS, so only 3 sections left.  I'm not sure how we can both work on this at the same time without stepping on each others' toes but I'm open to ideas if you want to create some of the models as well.

**Comment by whikloj** [comment]
I looked around and it is still a little unclear how the final product will look. Will the Bag model now have fields for all the models in the CAAIS application?

If so then I could alter that model (`Bag`) and start work on the django_rq worker methods to populate the new CAAIS with the form data and link it to the Bag.

**Comment by danloveg** [comment]
After this change is made, we will remove the `Bag` model and replace it with the `Metadata` model. So instead of a relationship between submissions and bags, there'll be a relationship between submissions and metadata. There'll be a few changes to the models in `recordtransfer`:

- Remove `Bag`
- Replace `OneToOneField` field in `Submission` with `Metadata`
- Move `part_of_group` field to `Submission`
- Move `upload_session` field to `Submission`
- Optional: Move `uuid` field to `Submission`
- Remove `accession_identifier` from `Submission`. This will be captured in `Metadata`
- Remove `level_of_detail` from `Submission`. This will be captured in `Metadata`

I'm hoping that this will make it simpler to create BagIt bags from. Calling `.flatten()` on an instance of `Metadata` will return a CSV-ready (or BagIt tag ready) dictionary. This will tie in with #90, as there won't need to be complicated logic with maintaining a Bag's state on the filesystem, it can just be generated whenever necessary. Some form of `Bag.make_bag()` or `BagAdmin.create_zipped_bag()` will need to be retained, triggered from the `SubmissionAdmin`. `Bag.update_bag()` and `Bag.remove_bag()` will not need to be kept. Similarly, `admin.update_filesystem_bag()` will not be needed.

It's a big logical shift, but will be necessary to keep things organized and clean for the future.

**Comment by whikloj** [comment]
Ok, so I am making the changes you suggest and removing `Bag`. This change is large and still not fully solid in my mind, but currently you can make a zipped bag from the `BagAdmin`. This seems like it will be the only bag instance anymore, so combining the calls (or having `create_zipped_bag` call `make_bag`) makes sense. 

Do we want the path of the zipped Bag stored in the Submission now that the `Bag` model is gone? 
Just thinking about the following case:
1. Admin makes a bag from `Submission`.
2. Admin updates/changes/adds some metadata.
3. Admin makes the bag again.

**Comment by danloveg** [comment]
Closed by #153
